# Call insar_timeseries for multiple years
name: InSAR_Pipeline
run-name: ${{ inputs.burstId }} ${{ inputs.polarization }} ${{ inputs.looks }} ${{ inputs.npairs }}

on:
  workflow_dispatch:
    inputs:
      burstId:
        type: string
        required: true
        description: ESA Burst Identifier (RelativeObit, ID, Subswath)
        default: '012_023790_IW1'
      polarization:
        type: choice
        required: true
        description: Polarization
        default: 'VV'
        options: ['VV', 'VH', 'HH']
      looks:
        type: choice
        required: true
        description: Range x Azimuth Looks
        default: '20x4'
        options: ['20x4','10x2','5x1']
      npairs:
        type: choice
        required: true
        description: Number of Pairs per Reference
        default: '3'
        options: ['3','2','1']

jobs:
    timeseries:
        strategy:
            fail-fast: false
            matrix:
                #year: [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
                year: [2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]
        uses: ./.github/workflows/insar_timeseries.yml
        with: 
            burstId: ${{ inputs.burstId }}
            year: ${{ matrix.year }}
            polarization: ${{ inputs.polarization }}
            looks: ${{ inputs.looks }}
            npairs: ${{ inputs.npairs }}
        secrets: inherit
